# Introduction To NumPy...

    >_ NumPy, Numerical Python.

    >_ Faster then normal python lists, Useful in ML calculations..

In [33]:
import numpy as np

# 1. Datatypes & Attributes ;

    >_  NumPy has only one datatype named " ndarray ".

    >_ " ndarray " means, n dimentional array..

In [34]:
ArrayOne = np.array([1, 2, 3])
ArrayOne

array([1, 2, 3])

In [35]:
type(ArrayOne)

numpy.ndarray

In [36]:
ArrayTwo = np.array([[1 , 2, 3],
                     [4, 5, 6]])
ArrayTwo

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
type(ArrayTwo)

numpy.ndarray

In [38]:
ArrayTwo.shape

(2, 3)

In [39]:
ArrayThree = np.array([[[9.0, 8, 7],
                        [6, 5.0, 4],
                        [3, 2, 1.0]]])
ArrayThree

array([[[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]]])

In [40]:
ArrayThree.shape

(1, 3, 3)

In [41]:
ArrayFour = np.array([[[3, 6, 9],
                        [9, 6, 3],
                        [6, 9, 3]],
                        
                        [[33, 66, 99],
                        [99,66,33],
                        [66, 99, 33]]])

# ArrayFour
ArrayFour.shape

(2, 3, 3)

In [42]:
ArrayOne

array([1, 2, 3])

In [43]:
ArrayTwo

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
ArrayThree

array([[[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]]])

In [45]:
ArrayFour
# ArrayFour.shape

array([[[ 3,  6,  9],
        [ 9,  6,  3],
        [ 6,  9,  3]],

       [[33, 66, 99],
        [99, 66, 33],
        [66, 99, 33]]])

# Some NumPy function/attributes...

In [46]:
ArrayOne.ndim, ArrayTwo.ndim, ArrayThree.ndim, ArrayFour.ndim

(1, 2, 3, 3)

In [47]:
ArrayOne.dtype, ArrayTwo.dtype, ArrayThree.dtype, ArrayFour.dtype

(dtype('int32'), dtype('int32'), dtype('float64'), dtype('int32'))

In [48]:
ArrayOne.size, ArrayTwo.size, ArrayThree.size, ArrayFour.size

(3, 6, 9, 18)

In [49]:
type(ArrayOne), type(ArrayTwo), type(ArrayThree), type(ArrayFour)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating pandas's DataFrame from NumPy's ndarray

In [50]:
import pandas

## >_ You must pass 2d array

In [51]:
DataFrameOne = pandas.DataFrame(ArrayTwo)
DataFrameOne

0  1  2
0  1  2  3
1  4  5  6

# 2. Creating Arrays...

In [52]:
import numpy

In [53]:
simple_array = numpy.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [54]:
ones_array = numpy.ones((2, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
zeros_array = numpy.zeros((4, 5))
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
range_array = numpy.arange(1, 10, 2)
range_array

array([1, 3, 5, 7, 9])

In [57]:
randint_array = numpy.random.randint(0, 10, size=(3,5))
randint_array

array([[7, 0, 5, 0, 1],
       [4, 1, 2, 2, 4],
       [8, 0, 6, 0, 4]])

In [58]:
randint_array.shape

(3, 5)

In [59]:
random_array = numpy.random.random(size=(6, 3))
random_array

array([[0.84378709, 0.48929125, 0.5401196 ],
       [0.82612808, 0.52160434, 0.14259934],
       [0.30226361, 0.80702268, 0.31949503],
       [0.02122574, 0.4824458 , 0.02602627],
       [0.50557406, 0.91803002, 0.20696613],
       [0.92573278, 0.27732305, 0.17606212]])

In [60]:
rand_array = numpy.random.rand(3, 4)
rand_array

array([[0.99030119, 0.69265062, 0.75214003, 0.11621659],
       [0.08600072, 0.66562461, 0.32957136, 0.36165062],
       [0.526111  , 0.42472996, 0.81978073, 0.57128475]])

    >_ Pseudo random numbers ...

In [61]:
numpy.random.seed(seed=1)
RandomOne = numpy.random.randint(0, 10, size=(5, 3))
RandomOne

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

## >_ seed(), sets the random numbers same each time seed's value is same...

In [62]:
numpy.random.seed(seed=3)
RandomTwo = numpy.random.random(size=(6, 4))
RandomTwo

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761],
       [0.89294695, 0.89629309, 0.12558531, 0.20724288],
       [0.0514672 , 0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 , 0.59086282],
       [0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774]])

In [63]:
RandomThree = numpy.random.random(size=(6, 4))
RandomThree

array([[0.54464902, 0.78031476, 0.30636353, 0.22195788],
       [0.38797126, 0.93638365, 0.97599542, 0.67238368],
       [0.90283411, 0.84575087, 0.37799404, 0.09221701],
       [0.6534109 , 0.55784076, 0.36156476, 0.2250545 ],
       [0.40651992, 0.46894025, 0.26923558, 0.29179277],
       [0.4576864 , 0.86053391, 0.5862529 , 0.28348786]])

In [64]:
RandomThree.shape

(6, 4)

# 3. Viewing arrays and matrices